# Generated by Django 5.2.9 on 2025-12-07 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_friends_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='date',
        ),
        migrations.RemoveField(
            model_name='cards',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='cards',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='cards',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='friends',
            name='image',
        ),
        migrations.RemoveField(
            model_name='friends',
            name='index',
        ),
        migrations.RemoveField(
            model_name='friends',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='phones',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='users',
            name='about',
        ),
        migrations.RemoveField(
            model_name='users',
            name='fatherName',
        ),
        migrations.RemoveField(
            model_name='users',
            name='idNumber',
        ),
        migrations.RemoveField(
            model_name='users',
            name='image',
        ),
        migrations.RemoveField(
            model_name='users',
            name='isCar',
        ),
        migrations.RemoveField(
            model_name='users',
            name='isCourt',
        ),
        migrations.RemoveField(
            model_name='users',
            name='passportNumber',
        ),
        migrations.RemoveField(
            model_name='workers',
            name='admin',
        ),
        migrations.AddField(
            model_name='cards',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cards',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='api.users'),
        ),
        migrations.AddField(
            model_name='friends',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friends', to='api.users'),
        ),
        migrations.AddField(
            model_name='phones',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='api.users'),
        ),
        migrations.AddField(
            model_name='users',
            name='id_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='passport_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workers',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cards',
            name='number',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='phones',
            name='number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
